name: Checking the code pushed in new branches before pull request            # optional 
on: 
  push:
    branches: 
      - html_ftadd
      - new_ftadd
      - webchange
      - terraform

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check the pushed code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: install required dependencies
        run:  npm install