name: Creating an ec2 instance         # optional 
on:
  workflow_dispatch:
    inputs:
      ec2_name:
        description: ec2 name
        required: true
        default: CICD test
        type: string
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'terraform/modules/**'
  #     - todo_app

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working_directory: terraform
    steps:

      - name: Check terraform code
        uses: actions/checkout@v3
       
      - name: Verify Terraform version
        run: terraform --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS-ACCESS-KEY-ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS-SECRET-ACCESS-KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS-REGION: us-east-1

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init          
        run: terraform init 

      - name: Terraform validation
        run: terraform validate

      - name: Terraform apply
        run: |
          working_directory
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve 
        

