
name: Terraform tasks defined to deploy ec2 instance         # optional 
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - todo_app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check terraform code
        uses: actions/checkout@v3
       
      - name: Verify Terraform version
        run: terraform --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS-ACCESS-KEY-ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS-SECRET-ACCESS-KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS-REGION: us-east-1

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_wrapper: false

      - name: Terraform init          
        run: terraform init -input=false

      - name: Terraform validation
        run: terraform validate

      - name: Terraform apply
        run: |
         cd /terraform/main/
         terraform init
         terraform plan
         terraform apply -auto-approve -input=false
        

